---
title: "Practica 1"
author: "Brian Sandoval"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(tidyverse)
#epa_http <- read_table("C:/Users/briansj/Documents/Trabajo01/epa-http.csv", col_names = FALSE)
epa_http <- read_table("~/Downloads/Practica01-main/epa-http.csv", col_names = FALSE)
colnames(epa_http) <- c("Origen","Tiempo","Tipo Peticion", "URL", "Version","Respuesta","Bytes")
#View(epa_http)

```

## Practica 01 - Data Science

***Pregunta 01:***

1.- Dado un registro de vehículos que circulan por una autopista, disponemos de su marca y modelo, país de matriculación, y tipo de vehículo (por número de ruedas). Con tal de ajustar precios de los peajes, ¿Cuántos vehículos tenemos por tipo? ¿Cuál es el tipo más frecuente? ¿De qué países tenemos más vehículos?

La clasificación de la pregunta es predictiva, puesto que, de una data de frecuencia de vehículos, se puede predecir los tipos de valores nuevos que usan las personas y de igual forma es clasificada descriptiva por que se desea saber el número de países recurrentes que circulan en la autopista.

2.- Dado un registro de visualizaciones de un servicio de video-on-demand, donde disponemos de los datos del usuario, de la película seleccionada, fecha de visualización y categoría de la película, queremos saber ¿Hay alguna preferencia en cuanto a género literario según los usuarios y su rango de edad?

La clasificación de la pregunta es exploratoria, puesto que se esta preguntando sobre la preferencia del genero de los usuarios. Ello conlleva en explorar dentro de la base de datos sobre el gusto de los usuarios.

3.- Dado un registro de peticiones a un sitio web, vemos que las peticiones que provienen de una red de telefonía concreta acostumbran a ser incorrectas y provocarnos errores de servicio. ¿Podemos determina si en el futuro, los próximos mensajes de esa red seguirán dando problemas? ¿Hemos notado el mismo efecto en otras redes de telefonía?

La clasificación de la pregunta es casuales, porque se requiere ver los resultados de los mensajes futuros en caso sigan dando problemas o no. De igual forma es exploratoria porque se requiere investigar si existe relación con otras redes de telefonía.

4.- Dado los registros de usuarios de un servicio de compras por internet, los usuarios pueden agruparse por preferencias de productos comprados. Queremos saber si ¿Es posible que, dado un usuario al azar y según su historial, pueda ser directamente asignado a un o diversos grupos?

La clasificación de la pregunta es predictiva, por que de acuerdo a los datos obtenidos se requiere revisar si puede ser asignado a uno o diversos grupos de acuerdo al historial de productos comprados.

**Pregunta 02:**

Considera el siguiente escenario: Sabemos que un usuario de nuestra red empresarial ha estado usando esta para fines no relacionados con el trabajo, como por ejemplo tener un servicio web no autorizado abierto a la red (otros usuarios tienen servicios web activados y autorizados). No queremos tener que rastrear los puertos de cada PC, y sabemos que la actividad puede haber cesado. Pero podemos acceder a los registros de conexiones TCP de cada máquina de cada trabajador (hacia donde abre conexión un PC concreto). Sabemos que nuestros clientes se conectan desde lugares remotos de forma legítima, como parte de nuestro negocio, y que un trabajador puede haber habilitado temporalmente servicios de prueba. Nuestro objetivo es reducir lo posible la lista de posibles culpables, con tal de explicarles que por favor no expongan nuestros sistemas sin permiso de los operadores o la dirección.

Explica con detalle cómo se podría proceder al análisis y resolución del problema mediante Data Science, indicando de donde se obtendrían los datos, qué tratamiento deberían recibir, qué preguntas hacerse para resolver el problema, qué datos y gráficos se obtendrían, y cómo se comunicarían estos.

En la información guardada debe de estar en un identificador único, nombre completo, apellidos, número de teléfono y correo, nacionalidad y su número de identificación. Teniendo esos datos básicos se puede crear un usuario y contraseña mediante el AD hacia los servicios de Internet asociados en la red empresarial, con ello se sabe mediante el registro asociado sobre la IP, puerto, contraseña, hora y fecha y el usuario que realiza esta comunicación. Se analiza mediante el registro de comunicación que realiza a qué sitio web y a dirección que usa. Teniendo esos usuarios, se realiza un protocolo de roles para identificar los permisos que se brinda y ejecuta dado poco a poco brindado.


------------------------------------------------------------------------

------------------------------------------------------------------------

**Introducción a R**

**Pregunta 1:** Una vez cargado el Dataset a analizar, comprobando que se cargan las IPs, el Timestamp, la Petición (Tipo, URL y Protocolo), Código de respuesta, y Bytes de reply.

1\. Cuales son las dimensiones del dataset cargado (número de filas y columnas)

RSPT: El data frame tiene `r nrow(epa_http)` filas y `r ncol(epa_http)` columnas

2\. Valor medio de la columna Bytes

RSPT: El valor medio es: `r 
tabla_flot <- epa_http
colnames(tabla_flot) <- c("Origen","Tiempo","Tipo Peticion", "URL", "Version","Respuesta","Bytes")
bytes<- as.numeric(tabla_flot$Bytes)
bytes[is.na(bytes)] <- 0
total_bytes <- mean(bytes)
total_bytes`.

**Pregunta 2:** De las diferentes IPs de origen accediendo al servidor, ¿cuantas pertenecen a una IP claramente educativa (que contenga ".edu")? RSPT: Se tiene un total de: `r 
url_edu <- epa_http[grepl(".edu", epa_http$Origen, ignore.case = FALSE), ]
numero_edu <- nrow(url_edu)
numero_edu` IPs.

**Pregunta 3:** De todas las peticiones recibidas por el servidor cual es la hora en la que hay mayor volumen de peticiones HTTP de tipo "GET"? RSPT: El mayor volumen es `r 
tablaflot3 <- epa_http
colnames(tablaflot3) <- c("Origen","Tiempo","Peti", "URL", "Version","Respuesta","Bytes")
totalGET <- tablaflot3[grepl("GET", tablaflot3$Peti, ignore.case = FALSE), ]
dia_hora <- substr(totalGET$Tiempo,5,6)
tabla_dia <- table(dia_hora)
tabla_ordenada <- sort(tabla_dia, decreasing = TRUE)
indice_max <- which.max(tabla_ordenada)
hora_max <- names(tabla_ordenada)[indice_max]
hora_max
` hrs.

**Pregunta 4:** De las peticiones hechas por instituciones educativas (.edu), ¿Cuantos bytes en total se han transmitido, en peticiones de descarga de ficheros de texto ".txt"?

RSPT: El total de bytes es `r 
tablaflot2 <- epa_http 
url_edu <- tablaflot2[grepl(".edu$", tablaflot2$Origen, ignore.case = FALSE), ] 
descargas_txt <-url_edu[grepl(".txt$", url_edu$URL, ignore.case = FALSE), ] 
bytes<- as.numeric(descargas_txt$Bytes) 
bytes[is.na(bytes)] 
suma <- mean(bytes) 
numero_sum <- sum(suma) 
numero_sum`.

**Pregunta 5:** Si separamos la petición en 3 partes (Tipo, URL, Protocolo), usando str_split y el separador " " (espacio), ¿cuantas peticiones buscan directamente la URL = "/"?

RSPT: Buscan directamente `r 
url_5 <- epa_http[grepl("^/$", epa_http$URL, ignore.case = FALSE), ]
numero_total5 <- nrow(url_5)
numero_total5
` URLs.

**Pregunta 6:** Aprovechando que hemos separado la petición en 3 partes (Tipo, URL, Protocolo) ¿Cuantas peticiones NO tienen como protocolo "HTTP/0.2"?

RSPT: Son en total `r 
url_http <- epa_http[!grepl("HTTP/0.2", epa_http$Version, ignore.case = FALSE), ]
numero_totalhttp <- nrow(url_http)
numero_totalhttp
` peticiones.
